# fly.toml app configuration file generated for blogbinder on 2023-11-11T20:21:22+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "blogbinder"
primary_region = "ams"

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]